#!/bin/bash
USAGE="$0 <username>"
if [ $# -ne 1 ]
then
  echo Usage: $USAGE
  exit 1
fi
for dir in  $(find /home/log -name '20*')
do
  for subdir in $(ls $dir)
  do
    user=$( echo $subdir | sed 's/-[^-]*-[^-]*-[^-]*$//'  )
    if [ $user ==  $1 ]
    then
      rm -fr $dir/$subdir
    fi
  done
done
